# THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE BY HAND.

from botocore.client import BaseClient

class SageMakerRuntime(BaseClient):

    def invoke_endpoint(self, **kwargs):
        """After you deploy a model into production using Amazon SageMaker hosting services, your client applications use this API to get inferences from the model hosted at the specified endpoint. 
        
         
        
        For an overview of Amazon SageMaker, see `How It Works <http://docs.aws.amazon.com/sagemaker/latest/dg/how-it-works.html>`__  
        
         
        
        Amazon SageMaker strips all POST headers except those supported by the API. Amazon SageMaker might add additional headers. You should not rely on the behavior of headers outside those enumerated in the request syntax. 
        
        
        
        See also: `AWS API Documentation <https://docs.aws.amazon.com/goto/WebAPI/runtime.sagemaker-2017-05-13/InvokeEndpoint>`_
        
        
        **Request Syntax** 
        ::
        
          response = client.invoke_endpoint(
              EndpointName='string',
              Body=b'bytes'|file,
              ContentType='string',
              Accept='string'
          )
        :type EndpointName: string
        :param EndpointName: **[REQUIRED]** 
        
          The name of the endpoint that you specified when you created the endpoint using the `CreateEndpoint <http://docs.aws.amazon.com/sagemaker/latest/dg/API_CreateEndpoint.html>`__ API. 
        
          
        
        
        :type Body: bytes or seekable file-like object
        :param Body: **[REQUIRED]** 
        
          Provides input data, in the format specified in the ``ContentType`` request header. Amazon SageMaker passes all of the data in the body to the model. 
        
          
        
        
        :type ContentType: string
        :param ContentType: 
        
          The MIME type of the input data in the request body.
        
          
        
        
        :type Accept: string
        :param Accept: 
        
          The desired MIME type of the inference in the response.
        
          
        
        
        
        :rtype: dict
        :returns: 
          
          **Response Syntax** 
        
          
          ::
        
            {
                'Body': StreamingBody(),
                'ContentType': 'string',
                'InvokedProductionVariant': 'string'
            }
          **Response Structure** 
        
          
        
          - *(dict) --* 
            
        
            - **Body** (:class:`.StreamingBody`) -- 
        
              Includes the inference provided by the model.
        
              
            
        
            - **ContentType** *(string) --* 
        
              The MIME type of the inference returned in the response body.
        
              
            
        
            - **InvokedProductionVariant** *(string) --* 
        
              Identifies the production variant that was invoked.
        
              
        
        """
        return self._make_api_call("InvokeEndpoint", kwargs)
