# THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE BY HAND.

from botocore.client import BaseClient

class Translate(BaseClient):

    def translate_text(self, **kwargs):
        """Translates input text from the source language to the target language. You can translate between English (en) and one of the following languages, or between one of the following languages and English.
        
         
        
         
        * Arabic (ar) 
         
        * Chinese (Simplified) (zh) 
         
        * French (fr) 
         
        * German (de) 
         
        * Portuguese (pt) 
         
        * Spanish (es) 
         
        
         
        
        To have Amazon Translate determine the source language of your text, you can specify ``auto`` in the ``SourceLanguageCode`` field. If you specify ``auto`` , Amazon Translate will call Amazon Comprehend to determine the source language.
        
        
        
        See also: `AWS API Documentation <https://docs.aws.amazon.com/goto/WebAPI/translate-2017-07-01/TranslateText>`_
        
        
        **Request Syntax** 
        ::
        
          response = client.translate_text(
              Text='string',
              SourceLanguageCode='string',
              TargetLanguageCode='string'
          )
        :type Text: string
        :param Text: **[REQUIRED]** 
        
          The text to translate.
        
          
        
        
        :type SourceLanguageCode: string
        :param SourceLanguageCode: **[REQUIRED]** 
        
          One of the supported language codes for the source text. If the ``TargetLanguageCode`` is not "en", the ``SourceLanguageCode`` must be "en".
        
           
        
          To have Amazon Translate determine the source language of your text, you can specify ``auto`` in the ``SourceLanguageCode`` field. If you specify ``auto`` , Amazon Translate will call Amazon Comprehend to determine the source language.
        
          
        
        
        :type TargetLanguageCode: string
        :param TargetLanguageCode: **[REQUIRED]** 
        
          One of the supported language codes for the target text. If the ``SourceLanguageCode`` is not "en", the ``TargetLanguageCode`` must be "en".
        
          
        
        
        
        :rtype: dict
        :returns: 
          
          **Response Syntax** 
        
          
          ::
        
            {
                'TranslatedText': 'string',
                'SourceLanguageCode': 'string',
                'TargetLanguageCode': 'string'
            }
          **Response Structure** 
        
          
        
          - *(dict) --* 
            
        
            - **TranslatedText** *(string) --* 
        
              The text translated into the target language.
        
              
            
        
            - **SourceLanguageCode** *(string) --* 
        
              The language code for the language of the input text. 
        
              
            
        
            - **TargetLanguageCode** *(string) --* 
        
              The language code for the language of the translated text. 
        
              
        
        """
        return self._make_api_call("TranslateText", kwargs)
