# THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE BY HAND.

from botocore.client import BaseClient

class Connect(BaseClient):

    def create_user(self, **kwargs):
        """Creates a new user account in your Amazon Connect instance.
        
        
        
        See also: `AWS API Documentation <https://docs.aws.amazon.com/goto/WebAPI/connect-2017-08-08/CreateUser>`_
        
        
        **Request Syntax** 
        ::
        
          response = client.create_user(
              Username='string',
              Password='string',
              IdentityInfo={
                  'FirstName': 'string',
                  'LastName': 'string',
                  'Email': 'string'
              },
              PhoneConfig={
                  'PhoneType': 'SOFT_PHONE'|'DESK_PHONE',
                  'AutoAccept': True|False,
                  'AfterContactWorkTimeLimit': 123,
                  'DeskPhoneNumber': 'string'
              },
              DirectoryUserId='string',
              SecurityProfileIds=[
                  'string',
              ],
              RoutingProfileId='string',
              HierarchyGroupId='string',
              InstanceId='string'
          )
        :type Username: string
        :param Username: **[REQUIRED]** 
        
          The user name in Amazon Connect for the user to create.
        
          
        
        
        :type Password: string
        :param Password: 
        
          The password for the user account to create. This is required if you are using Amazon Connect for identity management. If you are using SAML for identity management and include this parameter, an ``InvalidRequestException`` is returned.
        
          
        
        
        :type IdentityInfo: dict
        :param IdentityInfo: 
        
          Information about the user, including email address, first name, and last name.
        
          
        
        
          - **FirstName** *(string) --* 
        
            The first name used in the user account. This is required if you are using Amazon Connect or SAML for identity management.
        
            
        
          
          - **LastName** *(string) --* 
        
            The last name used in the user account. This is required if you are using Amazon Connect or SAML for identity management.
        
            
        
          
          - **Email** *(string) --* 
        
            The email address added to the user account. If you are using SAML for identity management and include this parameter, an ``InvalidRequestException`` is returned.
        
            
        
          
        
        :type PhoneConfig: dict
        :param PhoneConfig: **[REQUIRED]** 
        
          Specifies the phone settings for the user, including AfterContactWorkTimeLimit, AutoAccept, DeskPhoneNumber, and PhoneType.
        
          
        
        
          - **PhoneType** *(string) --* **[REQUIRED]** 
        
            The phone type selected for the user, either Soft phone or Desk phone.
        
            
        
          
          - **AutoAccept** *(boolean) --* 
        
            The Auto accept setting for the user, Yes or No.
        
            
        
          
          - **AfterContactWorkTimeLimit** *(integer) --* 
        
            The After Call Work (ACW) timeout setting, in seconds, for the user.
        
            
        
          
          - **DeskPhoneNumber** *(string) --* 
        
            The phone number for the user's desk phone.
        
            
        
          
        
        :type DirectoryUserId: string
        :param DirectoryUserId: 
        
          The unique identifier for the user account in the directory service directory used for identity management. If Amazon Connect is unable to access the existing directory, you can use the ``DirectoryUserId`` to authenticate users. If you include the parameter, it is assumed that Amazon Connect cannot access the directory. If the parameter is not included, the UserIdentityInfo is used to authenticate users from your existing directory.
        
           
        
          This parameter is required if you are using an existing directory for identity management in Amazon Connect when Amazon Connect cannot access your directory to authenticate users. If you are using SAML for identity management and include this parameter, an ``InvalidRequestException`` is returned.
        
          
        
        
        :type SecurityProfileIds: list
        :param SecurityProfileIds: **[REQUIRED]** 
        
          The unique identifier of the security profile to assign to the user created.
        
          
        
        
          - *(string) --* 
        
          
        
        :type RoutingProfileId: string
        :param RoutingProfileId: **[REQUIRED]** 
        
          The unique identifier for the routing profile to assign to the user created.
        
          
        
        
        :type HierarchyGroupId: string
        :param HierarchyGroupId: 
        
          The unique identifier for the hierarchy group to assign to the user created.
        
          
        
        
        :type InstanceId: string
        :param InstanceId: **[REQUIRED]** 
        
          The identifier for your Amazon Connect instance. To find the ID of your instance, open the AWS console and select Amazon Connect. Select the alias of the instance in the Instance alias column. The instance ID is displayed in the Overview section of your instance settings. For example, the instance ID is the set of characters at the end of the instance ARN, after instance/, such as 10a4c4eb-f57e-4d4c-b602-bf39176ced07.
        
          
        
        
        
        :rtype: dict
        :returns: 
          
          **Response Syntax** 
        
          
          ::
        
            {
                'UserId': 'string',
                'UserArn': 'string'
            }
          **Response Structure** 
        
          
        
          - *(dict) --* 
            
        
            - **UserId** *(string) --* 
        
              The unique identifier for the user account in Amazon Connect
        
              
            
        
            - **UserArn** *(string) --* 
        
              The Amazon Resource Name (ARN) of the user account created.
        
              
        
        """
        return self._make_api_call("CreateUser", kwargs)

    def delete_user(self, **kwargs):
        """Deletes a user account from Amazon Connect.
        
        
        
        See also: `AWS API Documentation <https://docs.aws.amazon.com/goto/WebAPI/connect-2017-08-08/DeleteUser>`_
        
        
        **Request Syntax** 
        ::
        
          response = client.delete_user(
              InstanceId='string',
              UserId='string'
          )
        :type InstanceId: string
        :param InstanceId: **[REQUIRED]** 
        
          The identifier for your Amazon Connect instance. To find the ID of your instance, open the AWS console and select Amazon Connect. Select the alias of the instance in the Instance alias column. The instance ID is displayed in the Overview section of your instance settings. For example, the instance ID is the set of characters at the end of the instance ARN, after instance/, such as 10a4c4eb-f57e-4d4c-b602-bf39176ced07.
        
          
        
        
        :type UserId: string
        :param UserId: **[REQUIRED]** 
        
          The unique identifier of the user to delete.
        
          
        
        
        
        :returns: None
        """
        return self._make_api_call("DeleteUser", kwargs)

    def describe_user(self, **kwargs):
        """Returns a ``User`` object that contains information about the user account specified by the ``UserId`` .
        
        
        
        See also: `AWS API Documentation <https://docs.aws.amazon.com/goto/WebAPI/connect-2017-08-08/DescribeUser>`_
        
        
        **Request Syntax** 
        ::
        
          response = client.describe_user(
              UserId='string',
              InstanceId='string'
          )
        :type UserId: string
        :param UserId: **[REQUIRED]** 
        
          Unique identifier for the user account to return.
        
          
        
        
        :type InstanceId: string
        :param InstanceId: **[REQUIRED]** 
        
          The identifier for your Amazon Connect instance. To find the ID of your instance, open the AWS console and select Amazon Connect. Select the alias of the instance in the Instance alias column. The instance ID is displayed in the Overview section of your instance settings. For example, the instance ID is the set of characters at the end of the instance ARN, after instance/, such as 10a4c4eb-f57e-4d4c-b602-bf39176ced07.
        
          
        
        
        
        :rtype: dict
        :returns: 
          
          **Response Syntax** 
        
          
          ::
        
            {
                'User': {
                    'Id': 'string',
                    'Arn': 'string',
                    'Username': 'string',
                    'IdentityInfo': {
                        'FirstName': 'string',
                        'LastName': 'string',
                        'Email': 'string'
                    },
                    'PhoneConfig': {
                        'PhoneType': 'SOFT_PHONE'|'DESK_PHONE',
                        'AutoAccept': True|False,
                        'AfterContactWorkTimeLimit': 123,
                        'DeskPhoneNumber': 'string'
                    },
                    'DirectoryUserId': 'string',
                    'SecurityProfileIds': [
                        'string',
                    ],
                    'RoutingProfileId': 'string',
                    'HierarchyGroupId': 'string'
                }
            }
          **Response Structure** 
        
          
        
          - *(dict) --* 
            
        
            - **User** *(dict) --* 
        
              A ``User`` object that contains information about the user account and configuration settings.
        
              
              
        
              - **Id** *(string) --* 
        
                The identifier of the user account.
        
                
              
        
              - **Arn** *(string) --* 
        
                The ARN of the user account.
        
                
              
        
              - **Username** *(string) --* 
        
                The user name assigned to the user account.
        
                
              
        
              - **IdentityInfo** *(dict) --* 
        
                A ``UserIdentityInfo`` object.
        
                
                
        
                - **FirstName** *(string) --* 
        
                  The first name used in the user account. This is required if you are using Amazon Connect or SAML for identity management.
        
                  
                
        
                - **LastName** *(string) --* 
        
                  The last name used in the user account. This is required if you are using Amazon Connect or SAML for identity management.
        
                  
                
        
                - **Email** *(string) --* 
        
                  The email address added to the user account. If you are using SAML for identity management and include this parameter, an ``InvalidRequestException`` is returned.
        
                  
            
              
        
              - **PhoneConfig** *(dict) --* 
        
                A ``UserPhoneConfig`` object.
        
                
                
        
                - **PhoneType** *(string) --* 
        
                  The phone type selected for the user, either Soft phone or Desk phone.
        
                  
                
        
                - **AutoAccept** *(boolean) --* 
        
                  The Auto accept setting for the user, Yes or No.
        
                  
                
        
                - **AfterContactWorkTimeLimit** *(integer) --* 
        
                  The After Call Work (ACW) timeout setting, in seconds, for the user.
        
                  
                
        
                - **DeskPhoneNumber** *(string) --* 
        
                  The phone number for the user's desk phone.
        
                  
            
              
        
              - **DirectoryUserId** *(string) --* 
        
                The directory Id for the user account in the existing directory used for identity management.
        
                
              
        
              - **SecurityProfileIds** *(list) --* 
        
                The identifier(s) for the security profile assigned to the user.
        
                
                
        
                - *(string) --* 
            
              
        
              - **RoutingProfileId** *(string) --* 
        
                The identifier of the routing profile assigned to the user.
        
                
              
        
              - **HierarchyGroupId** *(string) --* 
        
                The identifier for the hierarchy group assigned to the user.
        
                
          
        
        """
        return self._make_api_call("DescribeUser", kwargs)

    def describe_user_hierarchy_group(self, **kwargs):
        """Returns a ``HierarchyGroup`` object that includes information about a hierarchy group in your instance.
        
        
        
        See also: `AWS API Documentation <https://docs.aws.amazon.com/goto/WebAPI/connect-2017-08-08/DescribeUserHierarchyGroup>`_
        
        
        **Request Syntax** 
        ::
        
          response = client.describe_user_hierarchy_group(
              HierarchyGroupId='string',
              InstanceId='string'
          )
        :type HierarchyGroupId: string
        :param HierarchyGroupId: **[REQUIRED]** 
        
          The identifier for the hierarchy group to return.
        
          
        
        
        :type InstanceId: string
        :param InstanceId: **[REQUIRED]** 
        
          The identifier for your Amazon Connect instance. To find the ID of your instance, open the AWS console and select Amazon Connect. Select the alias of the instance in the Instance alias column. The instance ID is displayed in the Overview section of your instance settings. For example, the instance ID is the set of characters at the end of the instance ARN, after instance/, such as 10a4c4eb-f57e-4d4c-b602-bf39176ced07.
        
          
        
        
        
        :rtype: dict
        :returns: 
          
          **Response Syntax** 
        
          
          ::
        
            {
                'HierarchyGroup': {
                    'Id': 'string',
                    'Arn': 'string',
                    'Name': 'string',
                    'LevelId': 'string',
                    'HierarchyPath': {
                        'LevelOne': {
                            'Id': 'string',
                            'Arn': 'string',
                            'Name': 'string'
                        },
                        'LevelTwo': {
                            'Id': 'string',
                            'Arn': 'string',
                            'Name': 'string'
                        },
                        'LevelThree': {
                            'Id': 'string',
                            'Arn': 'string',
                            'Name': 'string'
                        },
                        'LevelFour': {
                            'Id': 'string',
                            'Arn': 'string',
                            'Name': 'string'
                        },
                        'LevelFive': {
                            'Id': 'string',
                            'Arn': 'string',
                            'Name': 'string'
                        }
                    }
                }
            }
          **Response Structure** 
        
          
        
          - *(dict) --* 
            
        
            - **HierarchyGroup** *(dict) --* 
        
              Returns a ``HierarchyGroup`` object.
        
              
              
        
              - **Id** *(string) --* 
        
                The identifier for the hierarchy group.
        
                
              
        
              - **Arn** *(string) --* 
        
                The Amazon Resource Name (ARN) for the hierarchy group.
        
                
              
        
              - **Name** *(string) --* 
        
                The name of the hierarchy group in your instance.
        
                
              
        
              - **LevelId** *(string) --* 
        
                The identifier for the level in the hierarchy group.
        
                
              
        
              - **HierarchyPath** *(dict) --* 
        
                A ``HierarchyPath`` object that contains information about the levels in the hierarchy group.
        
                
                
        
                - **LevelOne** *(dict) --* 
        
                  A ``HierarchyGroupSummary`` object that contains information about the level of the hierarchy group, including ARN, Id, and Name.
        
                  
                  
        
                  - **Id** *(string) --* 
        
                    The identifier of the hierarchy group.
        
                    
                  
        
                  - **Arn** *(string) --* 
        
                    The ARN for the hierarchy group.
        
                    
                  
        
                  - **Name** *(string) --* 
        
                    The name of the hierarchy group.
        
                    
              
                
        
                - **LevelTwo** *(dict) --* 
        
                  A ``HierarchyGroupSummary`` object that contains information about the level of the hierarchy group, including ARN, Id, and Name.
        
                  
                  
        
                  - **Id** *(string) --* 
        
                    The identifier of the hierarchy group.
        
                    
                  
        
                  - **Arn** *(string) --* 
        
                    The ARN for the hierarchy group.
        
                    
                  
        
                  - **Name** *(string) --* 
        
                    The name of the hierarchy group.
        
                    
              
                
        
                - **LevelThree** *(dict) --* 
        
                  A ``HierarchyGroupSummary`` object that contains information about the level of the hierarchy group, including ARN, Id, and Name.
        
                  
                  
        
                  - **Id** *(string) --* 
        
                    The identifier of the hierarchy group.
        
                    
                  
        
                  - **Arn** *(string) --* 
        
                    The ARN for the hierarchy group.
        
                    
                  
        
                  - **Name** *(string) --* 
        
                    The name of the hierarchy group.
        
                    
              
                
        
                - **LevelFour** *(dict) --* 
        
                  A ``HierarchyGroupSummary`` object that contains information about the level of the hierarchy group, including ARN, Id, and Name.
        
                  
                  
        
                  - **Id** *(string) --* 
        
                    The identifier of the hierarchy group.
        
                    
                  
        
                  - **Arn** *(string) --* 
        
                    The ARN for the hierarchy group.
        
                    
                  
        
                  - **Name** *(string) --* 
        
                    The name of the hierarchy group.
        
                    
              
                
        
                - **LevelFive** *(dict) --* 
        
                  A ``HierarchyGroupSummary`` object that contains information about the level of the hierarchy group, including ARN, Id, and Name.
        
                  
                  
        
                  - **Id** *(string) --* 
        
                    The identifier of the hierarchy group.
        
                    
                  
        
                  - **Arn** *(string) --* 
        
                    The ARN for the hierarchy group.
        
                    
                  
        
                  - **Name** *(string) --* 
        
                    The name of the hierarchy group.
        
                    
              
            
          
        
        """
        return self._make_api_call("DescribeUserHierarchyGroup", kwargs)

    def describe_user_hierarchy_structure(self, **kwargs):
        """Returns a ``HiearchyGroupStructure`` object, which contains data about the levels in the agent hierarchy.
        
        
        
        See also: `AWS API Documentation <https://docs.aws.amazon.com/goto/WebAPI/connect-2017-08-08/DescribeUserHierarchyStructure>`_
        
        
        **Request Syntax** 
        ::
        
          response = client.describe_user_hierarchy_structure(
              InstanceId='string'
          )
        :type InstanceId: string
        :param InstanceId: **[REQUIRED]** 
        
          The identifier for your Amazon Connect instance. To find the ID of your instance, open the AWS console and select Amazon Connect. Select the alias of the instance in the Instance alias column. The instance ID is displayed in the Overview section of your instance settings. For example, the instance ID is the set of characters at the end of the instance ARN, after instance/, such as 10a4c4eb-f57e-4d4c-b602-bf39176ced07.
        
          
        
        
        
        :rtype: dict
        :returns: 
          
          **Response Syntax** 
        
          
          ::
        
            {
                'HierarchyStructure': {
                    'LevelOne': {
                        'Id': 'string',
                        'Arn': 'string',
                        'Name': 'string'
                    },
                    'LevelTwo': {
                        'Id': 'string',
                        'Arn': 'string',
                        'Name': 'string'
                    },
                    'LevelThree': {
                        'Id': 'string',
                        'Arn': 'string',
                        'Name': 'string'
                    },
                    'LevelFour': {
                        'Id': 'string',
                        'Arn': 'string',
                        'Name': 'string'
                    },
                    'LevelFive': {
                        'Id': 'string',
                        'Arn': 'string',
                        'Name': 'string'
                    }
                }
            }
          **Response Structure** 
        
          
        
          - *(dict) --* 
            
        
            - **HierarchyStructure** *(dict) --* 
        
              A ``HierarchyStructure`` object.
        
              
              
        
              - **LevelOne** *(dict) --* 
        
                A ``HierarchyLevel`` object that contains information about the hierarchy group level.
        
                
                
        
                - **Id** *(string) --* 
        
                  The identifier for the hierarchy group level.
        
                  
                
        
                - **Arn** *(string) --* 
        
                  The ARN for the hierarchy group level.
        
                  
                
        
                - **Name** *(string) --* 
        
                  The name of the hierarchy group level.
        
                  
            
              
        
              - **LevelTwo** *(dict) --* 
        
                A ``HierarchyLevel`` object that contains information about the hierarchy group level.
        
                
                
        
                - **Id** *(string) --* 
        
                  The identifier for the hierarchy group level.
        
                  
                
        
                - **Arn** *(string) --* 
        
                  The ARN for the hierarchy group level.
        
                  
                
        
                - **Name** *(string) --* 
        
                  The name of the hierarchy group level.
        
                  
            
              
        
              - **LevelThree** *(dict) --* 
        
                A ``HierarchyLevel`` object that contains information about the hierarchy group level.
        
                
                
        
                - **Id** *(string) --* 
        
                  The identifier for the hierarchy group level.
        
                  
                
        
                - **Arn** *(string) --* 
        
                  The ARN for the hierarchy group level.
        
                  
                
        
                - **Name** *(string) --* 
        
                  The name of the hierarchy group level.
        
                  
            
              
        
              - **LevelFour** *(dict) --* 
        
                A ``HierarchyLevel`` object that contains information about the hierarchy group level.
        
                
                
        
                - **Id** *(string) --* 
        
                  The identifier for the hierarchy group level.
        
                  
                
        
                - **Arn** *(string) --* 
        
                  The ARN for the hierarchy group level.
        
                  
                
        
                - **Name** *(string) --* 
        
                  The name of the hierarchy group level.
        
                  
            
              
        
              - **LevelFive** *(dict) --* 
        
                A ``HierarchyLevel`` object that contains information about the hierarchy group level.
        
                
                
        
                - **Id** *(string) --* 
        
                  The identifier for the hierarchy group level.
        
                  
                
        
                - **Arn** *(string) --* 
        
                  The ARN for the hierarchy group level.
        
                  
                
        
                - **Name** *(string) --* 
        
                  The name of the hierarchy group level.
        
                  
            
          
        
        """
        return self._make_api_call("DescribeUserHierarchyStructure", kwargs)

    def get_federation_token(self, **kwargs):
        """Retrieves a token for federation.
        
        
        
        See also: `AWS API Documentation <https://docs.aws.amazon.com/goto/WebAPI/connect-2017-08-08/GetFederationToken>`_
        
        
        **Request Syntax** 
        ::
        
          response = client.get_federation_token(
              InstanceId='string'
          )
        :type InstanceId: string
        :param InstanceId: **[REQUIRED]** 
        
          The identifier for your Amazon Connect instance. To find the ID of your instance, open the AWS console and select Amazon Connect. Select the alias of the instance in the Instance alias column. The instance ID is displayed in the Overview section of your instance settings. For example, the instance ID is the set of characters at the end of the instance ARN, after instance/, such as 10a4c4eb-f57e-4d4c-b602-bf39176ced07.
        
          
        
        
        
        :rtype: dict
        :returns: 
          
          **Response Syntax** 
        
          
          ::
        
            {
                'Credentials': {
                    'AccessToken': 'string',
                    'AccessTokenExpiration': datetime(2015, 1, 1),
                    'RefreshToken': 'string',
                    'RefreshTokenExpiration': datetime(2015, 1, 1)
                }
            }
          **Response Structure** 
        
          
        
          - *(dict) --* 
            
        
            - **Credentials** *(dict) --* 
        
              The credentials to use for federation.
        
              
              
        
              - **AccessToken** *(string) --* 
        
                An access token generated for a federated user to access Amazon Connect
        
                
              
        
              - **AccessTokenExpiration** *(datetime) --* 
        
                A token generated with an expiration time for the session a user is logged in to Amazon Connect
        
                
              
        
              - **RefreshToken** *(string) --* 
        
                Renews a token generated for a user to access the Amazon Connect instance.
        
                
              
        
              - **RefreshTokenExpiration** *(datetime) --* 
        
                Renews the expiration timer for a generated token.
        
                
          
        
        """
        return self._make_api_call("GetFederationToken", kwargs)

    def list_routing_profiles(self, **kwargs):
        """Returns an array of ``RoutingProfileSummary`` objects that includes information about the routing profiles in your instance.
        
        
        
        See also: `AWS API Documentation <https://docs.aws.amazon.com/goto/WebAPI/connect-2017-08-08/ListRoutingProfiles>`_
        
        
        **Request Syntax** 
        ::
        
          response = client.list_routing_profiles(
              InstanceId='string',
              NextToken='string',
              MaxResults=123
          )
        :type InstanceId: string
        :param InstanceId: **[REQUIRED]** 
        
          The identifier for your Amazon Connect instance. To find the ID of your instance, open the AWS console and select Amazon Connect. Select the alias of the instance in the Instance alias column. The instance ID is displayed in the Overview section of your instance settings. For example, the instance ID is the set of characters at the end of the instance ARN, after instance/, such as 10a4c4eb-f57e-4d4c-b602-bf39176ced07.
        
          
        
        
        :type NextToken: string
        :param NextToken: 
        
          The token for the next set of results. Use the value returned in the previous response in the next request to retrieve the next set of results.
        
          
        
        
        :type MaxResults: integer
        :param MaxResults: 
        
          The maximum number of routing profiles to return in the response.
        
          
        
        
        
        :rtype: dict
        :returns: 
          
          **Response Syntax** 
        
          
          ::
        
            {
                'RoutingProfileSummaryList': [
                    {
                        'Id': 'string',
                        'Arn': 'string',
                        'Name': 'string'
                    },
                ],
                'NextToken': 'string'
            }
          **Response Structure** 
        
          
        
          - *(dict) --* 
            
        
            - **RoutingProfileSummaryList** *(list) --* 
        
              An array of ``RoutingProfileSummary`` objects that include the ARN, Id, and Name of the routing profile.
        
              
              
        
              - *(dict) --* 
        
                A ``RoutingProfileSummary`` object that contains information about a routing profile, including ARN, Id, and Name.
        
                
                
        
                - **Id** *(string) --* 
        
                  The identifier of the routing profile.
        
                  
                
        
                - **Arn** *(string) --* 
        
                  The ARN of the routing profile.
        
                  
                
        
                - **Name** *(string) --* 
        
                  The name of the routing profile.
        
                  
            
          
            
        
            - **NextToken** *(string) --* 
        
              A string returned in the response. Use the value returned in the response as the value of the NextToken in a subsequent request to retrieve the next set of results.
        
              
        
        """
        return self._make_api_call("ListRoutingProfiles", kwargs)

    def list_security_profiles(self, **kwargs):
        """Returns an array of SecurityProfileSummary objects that contain information about the security profiles in your instance, including the ARN, Id, and Name of the security profile.
        
        
        
        See also: `AWS API Documentation <https://docs.aws.amazon.com/goto/WebAPI/connect-2017-08-08/ListSecurityProfiles>`_
        
        
        **Request Syntax** 
        ::
        
          response = client.list_security_profiles(
              InstanceId='string',
              NextToken='string',
              MaxResults=123
          )
        :type InstanceId: string
        :param InstanceId: **[REQUIRED]** 
        
          The identifier for your Amazon Connect instance. To find the ID of your instance, open the AWS console and select Amazon Connect. Select the alias of the instance in the Instance alias column. The instance ID is displayed in the Overview section of your instance settings. For example, the instance ID is the set of characters at the end of the instance ARN, after instance/, such as 10a4c4eb-f57e-4d4c-b602-bf39176ced07.
        
          
        
        
        :type NextToken: string
        :param NextToken: 
        
          The token for the next set of results. Use the value returned in the previous response in the next request to retrieve the next set of results.
        
          
        
        
        :type MaxResults: integer
        :param MaxResults: 
        
          The maximum number of security profiles to return.
        
          
        
        
        
        :rtype: dict
        :returns: 
          
          **Response Syntax** 
        
          
          ::
        
            {
                'SecurityProfileSummaryList': [
                    {
                        'Id': 'string',
                        'Arn': 'string',
                        'Name': 'string'
                    },
                ],
                'NextToken': 'string'
            }
          **Response Structure** 
        
          
        
          - *(dict) --* 
            
        
            - **SecurityProfileSummaryList** *(list) --* 
        
              An array of ``SecurityProfileSummary`` objects.
        
              
              
        
              - *(dict) --* 
        
                A ``SecurityProfileSummary`` object that contains information about a security profile, including ARN, Id, Name.
        
                
                
        
                - **Id** *(string) --* 
        
                  The identifier of the security profile.
        
                  
                
        
                - **Arn** *(string) --* 
        
                  The ARN of the security profile.
        
                  
                
        
                - **Name** *(string) --* 
        
                  The name of the security profile.
        
                  
            
          
            
        
            - **NextToken** *(string) --* 
        
              A string returned in the response. Use the value returned in the response as the value of the NextToken in a subsequent request to retrieve the next set of results.
        
              
        
        """
        return self._make_api_call("ListSecurityProfiles", kwargs)

    def list_user_hierarchy_groups(self, **kwargs):
        """Returns a ``UserHierarchyGroupSummaryList`` , which is an array of ``HierarchyGroupSummary`` objects that contain information about the hierarchy groups in your instance.
        
        
        
        See also: `AWS API Documentation <https://docs.aws.amazon.com/goto/WebAPI/connect-2017-08-08/ListUserHierarchyGroups>`_
        
        
        **Request Syntax** 
        ::
        
          response = client.list_user_hierarchy_groups(
              InstanceId='string',
              NextToken='string',
              MaxResults=123
          )
        :type InstanceId: string
        :param InstanceId: **[REQUIRED]** 
        
          The identifier for your Amazon Connect instance. To find the ID of your instance, open the AWS console and select Amazon Connect. Select the alias of the instance in the Instance alias column. The instance ID is displayed in the Overview section of your instance settings. For example, the instance ID is the set of characters at the end of the instance ARN, after instance/, such as 10a4c4eb-f57e-4d4c-b602-bf39176ced07.
        
          
        
        
        :type NextToken: string
        :param NextToken: 
        
          The token for the next set of results. Use the value returned in the previous response in the next request to retrieve the next set of results.
        
          
        
        
        :type MaxResults: integer
        :param MaxResults: 
        
          The maximum number of hierarchy groups to return.
        
          
        
        
        
        :rtype: dict
        :returns: 
          
          **Response Syntax** 
        
          
          ::
        
            {
                'UserHierarchyGroupSummaryList': [
                    {
                        'Id': 'string',
                        'Arn': 'string',
                        'Name': 'string'
                    },
                ],
                'NextToken': 'string'
            }
          **Response Structure** 
        
          
        
          - *(dict) --* 
            
        
            - **UserHierarchyGroupSummaryList** *(list) --* 
        
              An array of ``HierarchyGroupSummary`` objects.
        
              
              
        
              - *(dict) --* 
        
                A ``HierarchyGroupSummary`` object that contains information about the hierarchy group, including ARN, Id, and Name.
        
                
                
        
                - **Id** *(string) --* 
        
                  The identifier of the hierarchy group.
        
                  
                
        
                - **Arn** *(string) --* 
        
                  The ARN for the hierarchy group.
        
                  
                
        
                - **Name** *(string) --* 
        
                  The name of the hierarchy group.
        
                  
            
          
            
        
            - **NextToken** *(string) --* 
        
              A string returned in the response. Use the value returned in the response as the value of the NextToken in a subsequent request to retrieve the next set of results.
        
              
        
        """
        return self._make_api_call("ListUserHierarchyGroups", kwargs)

    def list_users(self, **kwargs):
        """Returns a ``UserSummaryList`` , which is an array of ``UserSummary`` objects.
        
        
        
        See also: `AWS API Documentation <https://docs.aws.amazon.com/goto/WebAPI/connect-2017-08-08/ListUsers>`_
        
        
        **Request Syntax** 
        ::
        
          response = client.list_users(
              InstanceId='string',
              NextToken='string',
              MaxResults=123
          )
        :type InstanceId: string
        :param InstanceId: **[REQUIRED]** 
        
          The identifier for your Amazon Connect instance. To find the ID of your instance, open the AWS console and select Amazon Connect. Select the alias of the instance in the Instance alias column. The instance ID is displayed in the Overview section of your instance settings. For example, the instance ID is the set of characters at the end of the instance ARN, after instance/, such as 10a4c4eb-f57e-4d4c-b602-bf39176ced07.
        
          
        
        
        :type NextToken: string
        :param NextToken: 
        
          The token for the next set of results. Use the value returned in the previous response in the next request to retrieve the next set of results.
        
          
        
        
        :type MaxResults: integer
        :param MaxResults: 
        
          The maximum number of results to return in the response.
        
          
        
        
        
        :rtype: dict
        :returns: 
          
          **Response Syntax** 
        
          
          ::
        
            {
                'UserSummaryList': [
                    {
                        'Id': 'string',
                        'Arn': 'string',
                        'Username': 'string'
                    },
                ],
                'NextToken': 'string'
            }
          **Response Structure** 
        
          
        
          - *(dict) --* 
            
        
            - **UserSummaryList** *(list) --* 
        
              An array of ``UserSummary`` objects that contain information about the users in your instance.
        
              
              
        
              - *(dict) --* 
        
                A ``UserSummary`` object that contains Information about a user, including ARN, Id, and user name.
        
                
                
        
                - **Id** *(string) --* 
        
                  The identifier for the user account.
        
                  
                
        
                - **Arn** *(string) --* 
        
                  The ARN for the user account.
        
                  
                
        
                - **Username** *(string) --* 
        
                  The Amazon Connect user name for the user account.
        
                  
            
          
            
        
            - **NextToken** *(string) --* 
        
              A string returned in the response. Use the value returned in the response as the value of the NextToken in a subsequent request to retrieve the next set of results.
        
              
        
        """
        return self._make_api_call("ListUsers", kwargs)

    def start_outbound_voice_contact(self, **kwargs):
        """The ``StartOutboundVoiceContact`` operation initiates a contact flow to place an outbound call to a customer.
        
         
        
        There is a throttling limit placed on usage of the API that includes a RateLimit of 2 per second, and a BurstLimit of 5 per second.
        
         
        
        If you are using an IAM account, it must have permission to the ``connect:StartOutboundVoiceContact`` action.
        
        
        
        See also: `AWS API Documentation <https://docs.aws.amazon.com/goto/WebAPI/connect-2017-08-08/StartOutboundVoiceContact>`_
        
        
        **Request Syntax** 
        ::
        
          response = client.start_outbound_voice_contact(
              DestinationPhoneNumber='string',
              ContactFlowId='string',
              InstanceId='string',
              ClientToken='string',
              SourcePhoneNumber='string',
              QueueId='string',
              Attributes={
                  'string': 'string'
              }
          )
        :type DestinationPhoneNumber: string
        :param DestinationPhoneNumber: **[REQUIRED]** 
        
          The phone number of the customer in E.164 format.
        
          
        
        
        :type ContactFlowId: string
        :param ContactFlowId: **[REQUIRED]** 
        
          The identifier for the contact flow to connect the outbound call to.
        
           
        
          To find the ``ContactFlowId`` , open the contact flow you want to use in the Amazon Connect contact flow editor. The ID for the contact flow is displayed in the address bar as part of the URL. For example, the contact flow ID is the set of characters at the end of the URL, after 'contact-flow/' such as ``78ea8fd5-2659-4f2b-b528-699760ccfc1b`` .
        
          
        
        
        :type InstanceId: string
        :param InstanceId: **[REQUIRED]** 
        
          The identifier for your Amazon Connect instance. To find the ID of your instance, open the AWS console and select Amazon Connect. Select the alias of the instance in the Instance alias column. The instance ID is displayed in the Overview section of your instance settings. For example, the instance ID is the set of characters at the end of the instance ARN, after instance/, such as 10a4c4eb-f57e-4d4c-b602-bf39176ced07.
        
          
        
        
        :type ClientToken: string
        :param ClientToken: 
        
          A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. The token is valid for 7 days after creation. If a contact is already started, the contact ID is returned. If the contact is disconnected, a new contact is started.
        
          This field is autopopulated if not provided.
        
        
        :type SourcePhoneNumber: string
        :param SourcePhoneNumber: 
        
          The phone number, in E.164 format, associated with your Amazon Connect instance to use for the outbound call.
        
          
        
        
        :type QueueId: string
        :param QueueId: 
        
          The queue to add the call to. If you specify a queue, the phone displayed for caller ID is the phone number specified in the queue. If you do not specify a queue, the queue used will be the queue defined in the contact flow.
        
           
        
          To find the ``QueueId`` , open the queue you want to use in the Amazon Connect Queue editor. The ID for the queue is displayed in the address bar as part of the URL. For example, the queue ID is the set of characters at the end of the URL, after 'queue/' such as ``queue/aeg40574-2d01-51c3-73d6-bf8624d2168c`` .
        
          
        
        
        :type Attributes: dict
        :param Attributes: 
        
          Specify a custom key-value pair using an attribute map. The attributes are standard Amazon Connect attributes, and can be accessed in contact flows just like any other contact attributes.
        
           
        
          There can be up to 32,768 UTF-8 bytes across all key-value pairs. Attribute keys can include only alphanumeric, dash, and underscore characters.
        
           
        
          For example, if you want play a greeting when the customer answers the call, you can pass the customer name in attributes similar to the following:
        
          
        
        
          - *(string) --* Key for the key value pair to be used for additional attributes.
        
          
            - *(string) --* Value for the key value pair to be used for additional attributes.
        
            
        
        
        
        :rtype: dict
        :returns: 
          
          **Response Syntax** 
        
          
          ::
        
            {
                'ContactId': 'string'
            }
          **Response Structure** 
        
          
        
          - *(dict) --* 
            
        
            - **ContactId** *(string) --* 
        
              The unique identifier of this contact within your Amazon Connect instance.
        
              
        
        """
        return self._make_api_call("StartOutboundVoiceContact", kwargs)

    def stop_contact(self, **kwargs):
        """Ends the contact initiated by the ``StartOutboundVoiceContact`` operation.
        
         
        
        If you are using an IAM account, it must have permission to the ``connect:StopContact`` action.
        
        
        
        See also: `AWS API Documentation <https://docs.aws.amazon.com/goto/WebAPI/connect-2017-08-08/StopContact>`_
        
        
        **Request Syntax** 
        ::
        
          response = client.stop_contact(
              ContactId='string',
              InstanceId='string'
          )
        :type ContactId: string
        :param ContactId: **[REQUIRED]** 
        
          The unique identifier of the contact to end.
        
          
        
        
        :type InstanceId: string
        :param InstanceId: **[REQUIRED]** 
        
          The identifier for your Amazon Connect instance. To find the ID of your instance, open the AWS console and select Amazon Connect. Select the alias of the instance in the Instance alias column. The instance ID is displayed in the Overview section of your instance settings. For example, the instance ID is the set of characters at the end of the instance ARN, after instance/, such as 10a4c4eb-f57e-4d4c-b602-bf39176ced07.
        
          
        
        
        
        :rtype: dict
        :returns: 
          
          **Response Syntax** 
        
          
          ::
        
            {}
          **Response Structure** 
        
          
        
          - *(dict) --* 
        
        """
        return self._make_api_call("StopContact", kwargs)

    def update_user_hierarchy(self, **kwargs):
        """Assigns the specified hierarchy group to the user.
        
        
        
        See also: `AWS API Documentation <https://docs.aws.amazon.com/goto/WebAPI/connect-2017-08-08/UpdateUserHierarchy>`_
        
        
        **Request Syntax** 
        ::
        
          response = client.update_user_hierarchy(
              HierarchyGroupId='string',
              UserId='string',
              InstanceId='string'
          )
        :type HierarchyGroupId: string
        :param HierarchyGroupId: 
        
          The identifier for the hierarchy group to assign to the user.
        
          
        
        
        :type UserId: string
        :param UserId: **[REQUIRED]** 
        
          The identifier of the user account to assign the hierarchy group to.
        
          
        
        
        :type InstanceId: string
        :param InstanceId: **[REQUIRED]** 
        
          The identifier for your Amazon Connect instance. To find the ID of your instance, open the AWS console and select Amazon Connect. Select the alias of the instance in the Instance alias column. The instance ID is displayed in the Overview section of your instance settings. For example, the instance ID is the set of characters at the end of the instance ARN, after instance/, such as 10a4c4eb-f57e-4d4c-b602-bf39176ced07.
        
          
        
        
        
        :returns: None
        """
        return self._make_api_call("UpdateUserHierarchy", kwargs)

    def update_user_identity_info(self, **kwargs):
        """Updates the identity information for the specified user in a ``UserIdentityInfo`` object, including email, first name, and last name.
        
        
        
        See also: `AWS API Documentation <https://docs.aws.amazon.com/goto/WebAPI/connect-2017-08-08/UpdateUserIdentityInfo>`_
        
        
        **Request Syntax** 
        ::
        
          response = client.update_user_identity_info(
              IdentityInfo={
                  'FirstName': 'string',
                  'LastName': 'string',
                  'Email': 'string'
              },
              UserId='string',
              InstanceId='string'
          )
        :type IdentityInfo: dict
        :param IdentityInfo: **[REQUIRED]** 
        
          A ``UserIdentityInfo`` object.
        
          
        
        
          - **FirstName** *(string) --* 
        
            The first name used in the user account. This is required if you are using Amazon Connect or SAML for identity management.
        
            
        
          
          - **LastName** *(string) --* 
        
            The last name used in the user account. This is required if you are using Amazon Connect or SAML for identity management.
        
            
        
          
          - **Email** *(string) --* 
        
            The email address added to the user account. If you are using SAML for identity management and include this parameter, an ``InvalidRequestException`` is returned.
        
            
        
          
        
        :type UserId: string
        :param UserId: **[REQUIRED]** 
        
          The identifier for the user account to update identity information for.
        
          
        
        
        :type InstanceId: string
        :param InstanceId: **[REQUIRED]** 
        
          The identifier for your Amazon Connect instance. To find the ID of your instance, open the AWS console and select Amazon Connect. Select the alias of the instance in the Instance alias column. The instance ID is displayed in the Overview section of your instance settings. For example, the instance ID is the set of characters at the end of the instance ARN, after instance/, such as 10a4c4eb-f57e-4d4c-b602-bf39176ced07.
        
          
        
        
        
        :returns: None
        """
        return self._make_api_call("UpdateUserIdentityInfo", kwargs)

    def update_user_phone_config(self, **kwargs):
        """Updates the phone configuration settings in the ``UserPhoneConfig`` object for the specified user.
        
        
        
        See also: `AWS API Documentation <https://docs.aws.amazon.com/goto/WebAPI/connect-2017-08-08/UpdateUserPhoneConfig>`_
        
        
        **Request Syntax** 
        ::
        
          response = client.update_user_phone_config(
              PhoneConfig={
                  'PhoneType': 'SOFT_PHONE'|'DESK_PHONE',
                  'AutoAccept': True|False,
                  'AfterContactWorkTimeLimit': 123,
                  'DeskPhoneNumber': 'string'
              },
              UserId='string',
              InstanceId='string'
          )
        :type PhoneConfig: dict
        :param PhoneConfig: **[REQUIRED]** 
        
          A ``UserPhoneConfig`` object that contains settings for ``AfterContactWorkTimeLimit`` , ``AutoAccept`` , ``DeskPhoneNumber`` , and ``PhoneType`` to assign to the user.
        
          
        
        
          - **PhoneType** *(string) --* **[REQUIRED]** 
        
            The phone type selected for the user, either Soft phone or Desk phone.
        
            
        
          
          - **AutoAccept** *(boolean) --* 
        
            The Auto accept setting for the user, Yes or No.
        
            
        
          
          - **AfterContactWorkTimeLimit** *(integer) --* 
        
            The After Call Work (ACW) timeout setting, in seconds, for the user.
        
            
        
          
          - **DeskPhoneNumber** *(string) --* 
        
            The phone number for the user's desk phone.
        
            
        
          
        
        :type UserId: string
        :param UserId: **[REQUIRED]** 
        
          The identifier for the user account to change phone settings for.
        
          
        
        
        :type InstanceId: string
        :param InstanceId: **[REQUIRED]** 
        
          The identifier for your Amazon Connect instance. To find the ID of your instance, open the AWS console and select Amazon Connect. Select the alias of the instance in the Instance alias column. The instance ID is displayed in the Overview section of your instance settings. For example, the instance ID is the set of characters at the end of the instance ARN, after instance/, such as 10a4c4eb-f57e-4d4c-b602-bf39176ced07.
        
          
        
        
        
        :returns: None
        """
        return self._make_api_call("UpdateUserPhoneConfig", kwargs)

    def update_user_routing_profile(self, **kwargs):
        """Assigns the specified routing profile to a user.
        
        
        
        See also: `AWS API Documentation <https://docs.aws.amazon.com/goto/WebAPI/connect-2017-08-08/UpdateUserRoutingProfile>`_
        
        
        **Request Syntax** 
        ::
        
          response = client.update_user_routing_profile(
              RoutingProfileId='string',
              UserId='string',
              InstanceId='string'
          )
        :type RoutingProfileId: string
        :param RoutingProfileId: **[REQUIRED]** 
        
          The identifier of the routing profile to assign to the user.
        
          
        
        
        :type UserId: string
        :param UserId: **[REQUIRED]** 
        
          The identifier for the user account to assign the routing profile to.
        
          
        
        
        :type InstanceId: string
        :param InstanceId: **[REQUIRED]** 
        
          The identifier for your Amazon Connect instance. To find the ID of your instance, open the AWS console and select Amazon Connect. Select the alias of the instance in the Instance alias column. The instance ID is displayed in the Overview section of your instance settings. For example, the instance ID is the set of characters at the end of the instance ARN, after instance/, such as 10a4c4eb-f57e-4d4c-b602-bf39176ced07.
        
          
        
        
        
        :returns: None
        """
        return self._make_api_call("UpdateUserRoutingProfile", kwargs)

    def update_user_security_profiles(self, **kwargs):
        """Update the security profiles assigned to the user.
        
        
        
        See also: `AWS API Documentation <https://docs.aws.amazon.com/goto/WebAPI/connect-2017-08-08/UpdateUserSecurityProfiles>`_
        
        
        **Request Syntax** 
        ::
        
          response = client.update_user_security_profiles(
              SecurityProfileIds=[
                  'string',
              ],
              UserId='string',
              InstanceId='string'
          )
        :type SecurityProfileIds: list
        :param SecurityProfileIds: **[REQUIRED]** 
        
          The identifiers for the security profiles to assign to the user.
        
          
        
        
          - *(string) --* 
        
          
        
        :type UserId: string
        :param UserId: **[REQUIRED]** 
        
          The identifier of the user account to assign the security profiles.
        
          
        
        
        :type InstanceId: string
        :param InstanceId: **[REQUIRED]** 
        
          The identifier for your Amazon Connect instance. To find the ID of your instance, open the AWS console and select Amazon Connect. Select the alias of the instance in the Instance alias column. The instance ID is displayed in the Overview section of your instance settings. For example, the instance ID is the set of characters at the end of the instance ARN, after instance/, such as 10a4c4eb-f57e-4d4c-b602-bf39176ced07.
        
          
        
        
        
        :returns: None
        """
        return self._make_api_call("UpdateUserSecurityProfiles", kwargs)
